"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INSTRUMENT_ESCROW_SEED = exports.MAKER_CONFIRMED_COLLATERAL = exports.TAKER_CONFIRMED_COLLATERAL = exports.DEFAULT_SETTLING_WINDOW = exports.DEFAULT_ACTIVE_WINDOW = exports.DEFAULT_LEG_MULTIPLIER = exports.DEFAULT_PRICE = exports.DEFAULT_INSTRUMENT_SIDE = exports.DEFAULT_INSTRUMENT_AMOUNT = exports.DEFAULT_ORDER_TYPE = exports.DEFAULT_FEES = exports.DEFAULT_COLLATERAL_FUNDED = exports.DEFAULT_TOKEN_AMOUNT = exports.DEFAULT_SOL_FOR_SIGNERS = exports.ABSOLUTE_PRICE_DECIMALS = exports.LEG_MULTIPLIER_DECIMALS = exports.EMPTY_LEG_SIZE = exports.QUOTE_ESCROW_SEED = exports.COLLATERAL_TOKEN_SEED = exports.COLLATERAL_SEED = exports.PROTOCOL_SEED = void 0;
const anchor_1 = require("@project-serum/anchor");
const types_1 = require("./types");
exports.PROTOCOL_SEED = "protocol";
exports.COLLATERAL_SEED = "collateral_info";
exports.COLLATERAL_TOKEN_SEED = "collateral_token";
exports.QUOTE_ESCROW_SEED = "quote_escrow";
exports.EMPTY_LEG_SIZE = 32 + 4 + 8 + 1;
exports.LEG_MULTIPLIER_DECIMALS = 9;
exports.ABSOLUTE_PRICE_DECIMALS = 9;
exports.DEFAULT_SOL_FOR_SIGNERS = 100000000000;
exports.DEFAULT_TOKEN_AMOUNT = 1000000000000000;
exports.DEFAULT_COLLATERAL_FUNDED = new anchor_1.BN(100000000000);
exports.DEFAULT_FEES = { takerBps: new anchor_1.BN(0), makerBps: new anchor_1.BN(0) };
exports.DEFAULT_ORDER_TYPE = types_1.OrderType.TwoWay;
exports.DEFAULT_INSTRUMENT_AMOUNT = new anchor_1.BN(1000000000);
exports.DEFAULT_INSTRUMENT_SIDE = types_1.Side.Bid;
exports.DEFAULT_PRICE = new anchor_1.BN(100).mul(new anchor_1.BN(10).pow(new anchor_1.BN(exports.ABSOLUTE_PRICE_DECIMALS)));
exports.DEFAULT_LEG_MULTIPLIER = new anchor_1.BN(1).mul(new anchor_1.BN(10).pow(new anchor_1.BN(exports.LEG_MULTIPLIER_DECIMALS)));
exports.DEFAULT_ACTIVE_WINDOW = 10;
exports.DEFAULT_SETTLING_WINDOW = 60;
exports.TAKER_CONFIRMED_COLLATERAL = new anchor_1.BN(3000000000);
exports.MAKER_CONFIRMED_COLLATERAL = new anchor_1.BN(1000000000);
exports.INSTRUMENT_ESCROW_SEED = "escrow";
